AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False          # it will remove Dense layer of VGG19 (WHY - because we are using our own Dense layer)
EPOCHS: 50
CLASSES: 5
WEIGHTS: imagenet
LEARNING_RATE: 0.01