AUGMENTATION: True
IMAGE_SIZE: [128, 128, 3] # as per VGG 16 model
BATCH_SIZE: 32
INCLUDE_TOP: False          # it will remove Dense layer of VGG19 (WHY - because we are using our own Dense layer)
EPOCHS: 1
CLASSES: 5
WEIGHTS: imagenet
LEARNING_RATE: 0.01